
#Account     = "AKIA4F42KEYBUUXTJN4W"
#Pwd         = "BMmcqXw7qNrZqalHdkEbaRiFwvi4WtLs1DoxQ4U4dVaI"
#Url         = "email-smtp.ap-south-1.amazonaws.com:587"

Account     = "ftcsmtp@gmail.com"
Pwd         = "bhsv psnr kucm vhyu"
Url         = "smtp.gmail.com:587"
FromRaw     = "Flattrade" 
From        = "ftcsmtp@gmail.com"
ReplyTo     = "support@flattrade.in"
