	WallDomain      = "localhost"
	WallAllowOrigin = "http://localhost:8080"
	WallAppName     = "WALLDEV"

    AccountsDomain      = "localhost"
	AccountsAllowOrigin = "http://localhost:8080"

    AuthAllowOrigin = "https://auth.flattrade.in"
	AuthAppName     = "AUTH"
	
	ValidateSSO = "Y"


