RegisterClientID="ST708.im.dgfdsg$asfdgfdsgf4353"

RegisterSecret="ST708.fdgmg540gvgfdgsl45e6545m43n5243l5fv0dgfd34m43m43m344345dsffgds4524326"

CreateCode ="http://token.flattrade.in/api/CreateCode"

GenerateToken ="http://token.flattrade.in/api/GenerateToken"

SendMail = "https://comusrv.flattrade.in/sendMail"

##############################

RegisterClientID="ft_spt"

RegisterSecret="uisdfuiuisdf99isefsdfsdsdsd"

CreateCode ="http://192.168.2.143:30081/api/CreateCode"

GenerateToken ="http://192.168.2.143:30081/api/GenerateToken"

SendMail = "http://192.168.2.101:29103/sendMail"
